// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ultiminer_Database.Migrations
{
    [DbContext(typeof(UltiminerContext))]
    [Migration("20220723110057_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Database.Models.DropTable", b =>
                {
                    b.Property<string>("NaturalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NaturalId");

                    b.ToTable("DropTables");

                    b.HasData(
                        new
                        {
                            NaturalId = "Table.Stone",
                            DisplayName = "Stone"
                        },
                        new
                        {
                            NaturalId = "Table.Treasure",
                            DisplayName = "Treasure"
                        },
                        new
                        {
                            NaturalId = "Table.Gems",
                            DisplayName = "Gem"
                        });
                });

            modelBuilder.Entity("Database.Models.DropTableResource", b =>
                {
                    b.Property<string>("DropTableId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ResourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.HasKey("DropTableId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("DropTableResources");

                    b.HasData(
                        new
                        {
                            DropTableId = "Table.Stone",
                            ResourceId = "Stone.Simple",
                            Rarity = 10
                        },
                        new
                        {
                            DropTableId = "Table.Stone",
                            ResourceId = "Stone.Slate",
                            Rarity = 15
                        },
                        new
                        {
                            DropTableId = "Table.Treasure",
                            ResourceId = "Treasure.Rod.Wooden",
                            Rarity = 10
                        },
                        new
                        {
                            DropTableId = "Table.Treasure",
                            ResourceId = "Treasure.Binding.Linen",
                            Rarity = 15
                        },
                        new
                        {
                            DropTableId = "Table.Treasure",
                            ResourceId = "Treasure.Cube.Brass",
                            Rarity = 50
                        },
                        new
                        {
                            DropTableId = "Table.Gems",
                            ResourceId = "Gem.Raw.Quartz",
                            Rarity = 10
                        },
                        new
                        {
                            DropTableId = "Table.Gems",
                            ResourceId = "Gem.Raw.Opal",
                            Rarity = 15
                        });
                });

            modelBuilder.Entity("Database.Models.Node", b =>
                {
                    b.Property<string>("NaturalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("NaturalId");

                    b.ToTable("Nodes");

                    b.HasData(
                        new
                        {
                            NaturalId = "Node.Stone",
                            DisplayName = "Stone",
                            Quantity = 4
                        },
                        new
                        {
                            NaturalId = "Node.Slate",
                            DisplayName = "Slate",
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("Database.Models.NodeDropTable", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DropTableId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxDropRarity")
                        .HasColumnType("int");

                    b.Property<int>("MinDropRarity")
                        .HasColumnType("int");

                    b.Property<int>("TableRarity")
                        .HasColumnType("int");

                    b.HasKey("NodeId", "DropTableId");

                    b.HasIndex("DropTableId");

                    b.ToTable("NodeDropTables");

                    b.HasData(
                        new
                        {
                            NodeId = "Node.Stone",
                            DropTableId = "Table.Stone",
                            MaxDropRarity = 10,
                            MinDropRarity = 0,
                            TableRarity = 10
                        },
                        new
                        {
                            NodeId = "Node.Stone",
                            DropTableId = "Table.Treasure",
                            MaxDropRarity = 15,
                            MinDropRarity = 0,
                            TableRarity = 100
                        },
                        new
                        {
                            NodeId = "Node.Stone",
                            DropTableId = "Table.Gems",
                            MaxDropRarity = 10,
                            MinDropRarity = 0,
                            TableRarity = 200
                        },
                        new
                        {
                            NodeId = "Node.Slate",
                            DropTableId = "Table.Stone",
                            MaxDropRarity = 15,
                            MinDropRarity = 0,
                            TableRarity = 10
                        },
                        new
                        {
                            NodeId = "Node.Slate",
                            DropTableId = "Table.Treasure",
                            MaxDropRarity = 50,
                            MinDropRarity = 0,
                            TableRarity = 100
                        },
                        new
                        {
                            NodeId = "Node.Slate",
                            DropTableId = "Table.Gems",
                            MaxDropRarity = 15,
                            MinDropRarity = 0,
                            TableRarity = 200
                        });
                });

            modelBuilder.Entity("Database.Models.Resource", b =>
                {
                    b.Property<string>("NaturalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NaturalId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            NaturalId = "Stone.Simple",
                            DisplayName = "Stone"
                        },
                        new
                        {
                            NaturalId = "Stone.Slate",
                            DisplayName = "Slate"
                        },
                        new
                        {
                            NaturalId = "Treasure.Rod.Wooden",
                            DisplayName = "Wooden Rod"
                        },
                        new
                        {
                            NaturalId = "Treasure.Binding.Linen",
                            DisplayName = "Linen Scrap"
                        },
                        new
                        {
                            NaturalId = "Treasure.Cube.Brass",
                            DisplayName = "Brass Cube"
                        },
                        new
                        {
                            NaturalId = "Gem.Raw.Quartz",
                            DisplayName = "Quartz"
                        },
                        new
                        {
                            NaturalId = "Gem.Raw.Opal",
                            DisplayName = "Opal"
                        });
                });

            modelBuilder.Entity("Database.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Database.Models.UserResource", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ResourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("UserResources");
                });

            modelBuilder.Entity("Database.Models.DropTableResource", b =>
                {
                    b.HasOne("Database.Models.DropTable", "DropTable")
                        .WithMany("Resources")
                        .HasForeignKey("DropTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DropTable");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Database.Models.NodeDropTable", b =>
                {
                    b.HasOne("Database.Models.DropTable", "DropTable")
                        .WithMany()
                        .HasForeignKey("DropTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Node", "Node")
                        .WithMany("DropTables")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DropTable");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Database.Models.UserResource", b =>
                {
                    b.HasOne("Database.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.User", "User")
                        .WithMany("Resources")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Models.DropTable", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Database.Models.Node", b =>
                {
                    b.Navigation("DropTables");
                });

            modelBuilder.Entity("Database.Models.User", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
